const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Touch,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Browser,
		C3.Plugins.Share,
		C3.Plugins.LocalStorage,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.shadowlight,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Behaviors.skymenTrail,
		C3.Plugins.Text,
		C3.Behaviors.Orbit,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Physics.Acts.SetBullet,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Acts.SetWrapping,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Spritefont2.Acts.SetLineHeight,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Audio.Acts.Seek,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.SetLength,
		C3.Behaviors.skymenTrail.Acts.SetWidthEnd,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.skymenTrail.Acts.Detach,
		C3.Behaviors.skymenTrail.Cnds.IsAttached,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Cnds.OnImageLoadingComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyLoadingFinished,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.AdBlockDetected,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.PokiSDKLoaded,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Orbit.Acts.SetRadius
	];
};
self.C3_JsPropNameTable = [
	{Parado: 0},
	{ContagemFora: 0},
	{TipoDePedra: 0},
	{LimiteSine: 0},
	{ChecagemEstatistica: 0},
	{TipoDePedraDois: 0},
	{LImiteSineDois: 0},
	{Tocada: 0},
	{DelayColisao: 0},
	{ShadowCaster: 0},
	{Pedra1: 0},
	{Pedra2: 0},
	{Pedra3: 0},
	{Pedra4: 0},
	{Pedra5: 0},
	{Pedra6: 0},
	{Pedra7: 0},
	{Pedra8: 0},
	{Pedra9: 0},
	{Pedra10: 0},
	{Pedra11: 0},
	{Touch: 0},
	{EmJogo: 0},
	{Linha: 0},
	{Physics: 0},
	{Piso: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Sine: 0},
	{TextoPontuacaoTotal: 0},
	{BotaoPause: 0},
	{Tween: 0},
	{MenuOpcoes: 0},
	{Pin: 0},
	{BotaoFechar: 0},
	{TextoPontosGanhos: 0},
	{BotaoInicio: 0},
	{BotaoSom: 0},
	{BotaoMusica: 0},
	{BotaoRestart: 0},
	{BotaoHome: 0},
	{PedraExemplo: 0},
	{Browser: 0},
	{FundoJogo: 0},
	{Poeira: 0},
	{TextoNext: 0},
	{Limite: 0},
	{MenuGameOver: 0},
	{BotaoRestart2: 0},
	{BotaoHome2: 0},
	{TextoPontosRecorde: 0},
	{Comemorar: 0},
	{Hominho1: 0},
	{Hominho2: 0},
	{Hominho3: 0},
	{Hominho4: 0},
	{TextoPontosRecordeInicio: 0},
	{TituloDoJogo: 0},
	{Espiral: 0},
	{PedraLogo: 0},
	{TextoNovoRecorde: 0},
	{TextoVideos: 0},
	{NumeroDaConquista: 0},
	{Conquistada: 0},
	{Conquista1: 0},
	{Conquista2: 0},
	{Conquista3: 0},
	{Conquista4: 0},
	{Conquista5: 0},
	{Conquista6: 0},
	{Conquista7: 0},
	{Conquista8: 0},
	{Conquista9: 0},
	{Conquista10: 0},
	{Conquista11: 0},
	{Conquista12: 0},
	{Conquista13: 0},
	{Conquista14: 0},
	{Conquista15: 0},
	{Conquista16: 0},
	{Conquista17: 0},
	{Conquista18: 0},
	{Conquista19: 0},
	{Conquista20: 0},
	{Conquista21: 0},
	{Conquista22: 0},
	{Conquista23: 0},
	{Conquista24: 0},
	{Conquista25: 0},
	{Conquista26: 0},
	{Conquista27: 0},
	{Conquista28: 0},
	{Pop: 0},
	{TelaMenuConquistas: 0},
	{IconeConquistaGrande: 0},
	{BotaoEukarya: 0},
	{BotaoConquistas: 0},
	{BotaoCompartilhar: 0},
	{BotaoAvaliar: 0},
	{Share: 0},
	{AvisoConquista: 0},
	{DMMono: 0},
	{Pontilhado: 0},
	{DMMono2: 0},
	{TituloConquistas: 0},
	{Estado: 0},
	{ConquistadaVez: 0},
	{AvisoConquistaMenu: 0},
	{LocalStorage: 0},
	{PokiSDK: 0},
	{Sine2: 0},
	{DragDrop: 0},
	{IconeBombinha: 0},
	{MenuBombinha: 0},
	{MenuBombinhaFechar: 0},
	{MenuBombinhaVideo: 0},
	{BotaoFechar2: 0},
	{FundoVerdeJogo: 0},
	{LinhaGuia: 0},
	{TouchValendo: 0},
	{FundoVerde: 0},
	{Anchor: 0},
	{TiledBackground: 0},
	{BotaoShareLandscape: 0},
	{BotaoHudLandscape: 0},
	{MenuVideoBombinha: 0},
	{Mouse: 0},
	{BotaoAjuda: 0},
	{TelaMenuConquistas3: 0},
	{TextoNext2: 0},
	{DMMonoAvisoVideo: 0},
	{Pontilhado2: 0},
	{DMMono4: 0},
	{ShadowLight: 0},
	{AreaDescolisao: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{BrilhoPedra: 0},
	{CirculoPontos: 0},
	{BombaReal: 0},
	{TelaAjuda: 0},
	{FecharAjuda: 0},
	{TextoShakeBomb: 0},
	{TextoQuantBombinha: 0},
	{DMMonoQuantBombinha: 0},
	{IconeBombinha2: 0},
	{TelaMenuVideoBombinha: 0},
	{PontilhadoVideo: 0},
	{IconeBombinhaVideo: 0},
	{BotaoMusica2: 0},
	{BotaoVideo: 0},
	{BotaoFecharVideo: 0},
	{TelaMenuGanhou: 0},
	{IconeBombinhaVideoGanho: 0},
	{Pop2: 0},
	{TelaMenuConquistas2: 0},
	{IconeConquistaGrande2: 0},
	{DMMono3: 0},
	{BotaoFechar3: 0},
	{BotaoIniciarJogo: 0},
	{FundoJogo2: 0},
	{BotaoVoltar: 0},
	{BotaoConquistas2: 0},
	{bege: 0},
	{BotaoOrientacao: 0},
	{TelaMenuOrientacao: 0},
	{DMMonoAvisoOrientacao: 0},
	{DMMonoAvisoOrientacao2: 0},
	{BotaoNegarOrientacao: 0},
	{BotaoAceitarOrientacao: 0},
	{DMMonoAjuda: 0},
	{FundoBranco: 0},
	{PontilhadoOrientacao: 0},
	{TelaAjuda2: 0},
	{TelaAjuda3: 0},
	{TelaAjuda4: 0},
	{TelaAjuda5: 0},
	{TelaAjuda6: 0},
	{TelaAjuda7: 0},
	{TelaAjuda8: 0},
	{PedraOriginaria: 0},
	{Rotate: 0},
	{Estrela: 0},
	{HandTouch: 0},
	{TrailRenderer: 0},
	{TrilhaLinha: 0},
	{ContadorLimiteBombinha: 0},
	{LimiteBombinha: 0},
	{TelaMenuStartPortrait: 0},
	{DMMonoAvisoStart: 0},
	{Text: 0},
	{ContadorTempoCapivara: 0},
	{CapivaraExistente: 0},
	{Sine3: 0},
	{Pedra12: 0},
	{Orbit: 0},
	{Orbital: 0},
	{SineFake: 0},
	{PedraFake: 0},
	{agua: 0},
	{PedraInterrogação: 0},
	{PedraFake2: 0},
	{Sequenciapedras: 0},
	{EstrelaDestaque: 0},
	{Pedras: 0},
	{PedraPequena: 0},
	{PedraMedia: 0},
	{PedraGrande: 0},
	{Botoes: 0},
	{PedrasDois: 0},
	{Hominhos: 0},
	{Conquistas: 0},
	{MenuConquistaEspecifico: 0},
	{Tween2: 0},
	{MenuConquistasGeral: 0},
	{Pin2: 0},
	{MenuVideo: 0},
	{Bombinha: 0},
	{Restart: 0},
	{ExistePedra1: 0},
	{ExistePedra2: 0},
	{ExistePedra3: 0},
	{ExistePedra4: 0},
	{ExistePedra5: 0},
	{ExistePedra6: 0},
	{ExistePedra7: 0},
	{ExistePedra8: 0},
	{ExistePedra9: 0},
	{ExistePedra10: 0},
	{ExistePedra11: 0},
	{POKI_LAST_AD_TAG2: 0},
	{POKI_HAS_AD_BLOCKER2: 0},
	{PK_GAMEPLAY_STOPPED2: 0},
	{ParadaPedra1: 0},
	{ParadaPedra2: 0},
	{ParadaPedra3: 0},
	{ParadaPedra4: 0},
	{TotalPedras: 0},
	{TotalPedra1: 0},
	{TotalPedra2: 0},
	{TotalPedra3: 0},
	{TotalPedra4: 0},
	{TotalPedra5: 0},
	{TotalPedra6: 0},
	{TotalPedra7: 0},
	{TotalPedra8: 0},
	{TotalPedra9: 0},
	{TotalPedra10: 0},
	{TotalPedra11: 0},
	{QuantPedras: 0},
	{QuantPedra1: 0},
	{QuantPedra2: 0},
	{QuantPedra3: 0},
	{QuantPedra4: 0},
	{QuantPedra5: 0},
	{QuantPedra6: 0},
	{QuantPedra7: 0},
	{QuantPedra8: 0},
	{QuantPedra9: 0},
	{QuantPedra10: 0},
	{QuantPedra11: 0},
	{TelaPedras: 0},
	{TelaPedra1: 0},
	{TelaPedra2: 0},
	{TelaPedra3: 0},
	{TelaPedra4: 0},
	{TelaPedra5: 0},
	{TelaPedra6: 0},
	{TelaPedra7: 0},
	{TelaPedra8: 0},
	{TelaPedra9: 0},
	{TelaPedra10: 0},
	{TelaPedra11: 0},
	{vida: 0},
	{HominhoComemorando: 0},
	{PedraRandom: 0},
	{NovoRecorde: 0},
	{ScoreAtual: 0},
	{ProximaPedra: 0},
	{MusicaLigada: 0},
	{SfxLigado: 0},
	{ScoreRecorde: 0},
	{ColisoesLimite: 0},
	{DiferentesPedras: 0},
	{DelayReporPedra: 0},
	{Tempo: 0},
	{TelaAtual: 0},
	{BombinhaUsadaTotal: 0},
	{BombinhaDaVez: 0},
	{PokiStart: 0},
	{DicaInicio: 0},
	{DicaBombinha: 0},
	{TamanhoFinalPedraLandscape: 0},
	{EstrelinhaDistancia: 0},
	{PrimeiroComecoLandscape: 0},
	{LimiteForaNumero: 0},
	{Var_TempoMostrandoConquista: 0},
	{ContagemDestaqueBombinha: 0},
	{BombinhaX: 0},
	{BombinhaY: 0},
	{tempoEspera: 0},
	{TocadaPedra1: 0},
	{TocadaPedra2: 0},
	{TocadaPedra3: 0},
	{TocadaPedra4: 0},
	{TocadaPedra5: 0},
	{TocadaPedra6: 0},
	{TocadaPedra7: 0},
	{TocadaPedra8: 0},
	{TocadaPedra9: 0},
	{TocadaPedra10: 0},
	{TocadaPedra11: 0},
	{TocadaPedra12: 0},
	{TocadaPedraTitulo: 0},
	{POKI_LAST_AD_TAG: 0},
	{POKI_HAS_AD_BLOCKER: 0},
	{PK_GAMEPLAY_STOPPED: 0},
	{tag: 0},
	{ConquistaAtiva: 0},
	{ConquistaNova: 0},
	{UltimoLayout: 0},
	{BombinhaX2: 0},
	{BombinhaY2: 0},
	{ExistePedra12: 0},
	{ExistePedra13: 0},
	{ExistePedra14: 0},
	{ExistePedra15: 0},
	{ExistePedra16: 0},
	{ExistePedra17: 0},
	{ExistePedra18: 0},
	{ExistePedra19: 0},
	{ExistePedra20: 0},
	{ExistePedra21: 0},
	{ExistePedra22: 0},
	{POKI_LAST_AD_TAG3: 0},
	{POKI_HAS_AD_BLOCKER3: 0},
	{PK_GAMEPLAY_STOPPED3: 0},
	{ParadaPedra5: 0},
	{ParadaPedra6: 0},
	{ParadaPedra7: 0},
	{ParadaPedra8: 0},
	{TotalPedras2: 0},
	{TotalPedra12: 0},
	{TotalPedra13: 0},
	{TotalPedra14: 0},
	{TotalPedra15: 0},
	{TotalPedra16: 0},
	{TotalPedra17: 0},
	{TotalPedra18: 0},
	{TotalPedra19: 0},
	{TotalPedra20: 0},
	{TotalPedra21: 0},
	{TotalPedra22: 0},
	{QuantPedras2: 0},
	{QuantPedra12: 0},
	{QuantPedra13: 0},
	{QuantPedra14: 0},
	{QuantPedra15: 0},
	{QuantPedra16: 0},
	{QuantPedra17: 0},
	{QuantPedra18: 0},
	{QuantPedra19: 0},
	{QuantPedra20: 0},
	{QuantPedra21: 0},
	{QuantPedra22: 0},
	{TelaPedras2: 0},
	{TelaPedra12: 0},
	{TelaPedra13: 0},
	{TelaPedra14: 0},
	{TelaPedra15: 0},
	{TelaPedra16: 0},
	{TelaPedra17: 0},
	{TelaPedra18: 0},
	{TelaPedra19: 0},
	{TelaPedra20: 0},
	{TelaPedra21: 0},
	{TelaPedra22: 0},
	{vida2: 0},
	{HominhoComemorando2: 0},
	{PedraRandom2: 0},
	{NovoRecorde2: 0},
	{ScoreAtual2: 0},
	{ProximaPedra2: 0},
	{MusicaLigada2: 0},
	{SfxLigado2: 0},
	{ScoreRecorde2: 0},
	{ColisoesLimite2: 0},
	{DiferentesPedras2: 0},
	{DelayReporPedra2: 0},
	{Tempo2: 0},
	{TelaAtual2: 0},
	{BombinhaUsadaTotal2: 0},
	{BombinhaDaVez2: 0},
	{PokiStart2: 0},
	{Restarted: 0},
	{TamanhoFinalPedraPortrait: 0},
	{ReporPedraPortrait: 0},
	{CameraAjusteY: 0},
	{Fases: 0},
	{PortraitVoltarMenu: 0},
	{RelogioAd: 0}
];

self.InstanceType = {
	Pedra1: class extends self.ISpriteInstance {},
	Pedra2: class extends self.ISpriteInstance {},
	Pedra3: class extends self.ISpriteInstance {},
	Pedra4: class extends self.ISpriteInstance {},
	Pedra5: class extends self.ISpriteInstance {},
	Pedra6: class extends self.ISpriteInstance {},
	Pedra7: class extends self.ISpriteInstance {},
	Pedra8: class extends self.ISpriteInstance {},
	Pedra9: class extends self.ISpriteInstance {},
	Pedra10: class extends self.ISpriteInstance {},
	Pedra11: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Linha: class extends self.ISpriteInstance {},
	Piso: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TextoPontuacaoTotal: class extends self.ISpriteFontInstance {},
	BotaoPause: class extends self.ISpriteInstance {},
	MenuOpcoes: class extends self.ISpriteInstance {},
	BotaoFechar: class extends self.ISpriteInstance {},
	TextoPontosGanhos: class extends self.ISpriteFontInstance {},
	BotaoInicio: class extends self.ISpriteInstance {},
	BotaoSom: class extends self.ISpriteInstance {},
	BotaoMusica: class extends self.ISpriteInstance {},
	BotaoRestart: class extends self.ISpriteInstance {},
	BotaoHome: class extends self.ISpriteInstance {},
	PedraExemplo: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	FundoJogo: class extends self.ISpriteInstance {},
	Poeira: class extends self.ISpriteInstance {},
	TextoNext: class extends self.ISpriteFontInstance {},
	Limite: class extends self.ISpriteInstance {},
	MenuGameOver: class extends self.ISpriteInstance {},
	BotaoRestart2: class extends self.ISpriteInstance {},
	BotaoHome2: class extends self.ISpriteInstance {},
	TextoPontosRecorde: class extends self.ISpriteFontInstance {},
	Hominho1: class extends self.ISpriteInstance {},
	Hominho2: class extends self.ISpriteInstance {},
	Hominho3: class extends self.ISpriteInstance {},
	Hominho4: class extends self.ISpriteInstance {},
	TextoPontosRecordeInicio: class extends self.ISpriteFontInstance {},
	TituloDoJogo: class extends self.ISpriteInstance {},
	Espiral: class extends self.ISpriteInstance {},
	PedraLogo: class extends self.ISpriteInstance {},
	TextoNovoRecorde: class extends self.ISpriteFontInstance {},
	TextoVideos: class extends self.ISpriteInstance {},
	Conquista1: class extends self.ISpriteInstance {},
	Conquista2: class extends self.ISpriteInstance {},
	Conquista3: class extends self.ISpriteInstance {},
	Conquista4: class extends self.ISpriteInstance {},
	Conquista5: class extends self.ISpriteInstance {},
	Conquista6: class extends self.ISpriteInstance {},
	Conquista7: class extends self.ISpriteInstance {},
	Conquista8: class extends self.ISpriteInstance {},
	Conquista9: class extends self.ISpriteInstance {},
	Conquista10: class extends self.ISpriteInstance {},
	Conquista11: class extends self.ISpriteInstance {},
	Conquista12: class extends self.ISpriteInstance {},
	Conquista13: class extends self.ISpriteInstance {},
	Conquista14: class extends self.ISpriteInstance {},
	Conquista15: class extends self.ISpriteInstance {},
	Conquista16: class extends self.ISpriteInstance {},
	Conquista17: class extends self.ISpriteInstance {},
	Conquista18: class extends self.ISpriteInstance {},
	Conquista19: class extends self.ISpriteInstance {},
	Conquista20: class extends self.ISpriteInstance {},
	Conquista21: class extends self.ISpriteInstance {},
	Conquista22: class extends self.ISpriteInstance {},
	Conquista23: class extends self.ISpriteInstance {},
	Conquista24: class extends self.ISpriteInstance {},
	Conquista25: class extends self.ISpriteInstance {},
	Conquista26: class extends self.ISpriteInstance {},
	Conquista27: class extends self.ISpriteInstance {},
	Conquista28: class extends self.ISpriteInstance {},
	TelaMenuConquistas: class extends self.ISpriteInstance {},
	IconeConquistaGrande: class extends self.ISpriteInstance {},
	BotaoEukarya: class extends self.ISpriteInstance {},
	BotaoConquistas: class extends self.ISpriteInstance {},
	BotaoCompartilhar: class extends self.ISpriteInstance {},
	BotaoAvaliar: class extends self.ISpriteInstance {},
	Share: class extends self.IInstance {},
	AvisoConquista: class extends self.ISpriteInstance {},
	DMMono: class extends self.ISpriteFontInstance {},
	Pontilhado: class extends self.ISpriteInstance {},
	DMMono2: class extends self.ISpriteFontInstance {},
	TituloConquistas: class extends self.ISpriteInstance {},
	AvisoConquistaMenu: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	PokiSDK: class extends self.IInstance {},
	IconeBombinha: class extends self.ISpriteInstance {},
	MenuBombinha: class extends self.ISpriteInstance {},
	MenuBombinhaFechar: class extends self.ISpriteInstance {},
	MenuBombinhaVideo: class extends self.ISpriteInstance {},
	BotaoFechar2: class extends self.ISpriteInstance {},
	FundoVerdeJogo: class extends self.ISpriteInstance {},
	LinhaGuia: class extends self.ISpriteInstance {},
	FundoVerde: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	BotaoShareLandscape: class extends self.ISpriteInstance {},
	BotaoHudLandscape: class extends self.ISpriteInstance {},
	MenuVideoBombinha: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BotaoAjuda: class extends self.ISpriteInstance {},
	TelaMenuConquistas3: class extends self.ISpriteInstance {},
	TextoNext2: class extends self.ISpriteFontInstance {},
	DMMonoAvisoVideo: class extends self.ISpriteFontInstance {},
	Pontilhado2: class extends self.ISpriteInstance {},
	DMMono4: class extends self.ISpriteFontInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	AreaDescolisao: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	BrilhoPedra: class extends self.ISpriteInstance {},
	CirculoPontos: class extends self.ISpriteInstance {},
	BombaReal: class extends self.ISpriteInstance {},
	TelaAjuda: class extends self.ISpriteInstance {},
	FecharAjuda: class extends self.ISpriteInstance {},
	TextoShakeBomb: class extends self.ISpriteFontInstance {},
	TextoQuantBombinha: class extends self.ISpriteFontInstance {},
	DMMonoQuantBombinha: class extends self.ISpriteFontInstance {},
	IconeBombinha2: class extends self.ISpriteInstance {},
	TelaMenuVideoBombinha: class extends self.ISpriteInstance {},
	PontilhadoVideo: class extends self.ISpriteInstance {},
	IconeBombinhaVideo: class extends self.ISpriteInstance {},
	BotaoMusica2: class extends self.ISpriteInstance {},
	BotaoVideo: class extends self.ISpriteInstance {},
	BotaoFecharVideo: class extends self.ISpriteInstance {},
	TelaMenuGanhou: class extends self.ISpriteInstance {},
	IconeBombinhaVideoGanho: class extends self.ISpriteInstance {},
	TelaMenuConquistas2: class extends self.ISpriteInstance {},
	IconeConquistaGrande2: class extends self.ISpriteInstance {},
	DMMono3: class extends self.ISpriteFontInstance {},
	BotaoFechar3: class extends self.ISpriteInstance {},
	BotaoIniciarJogo: class extends self.ISpriteInstance {},
	FundoJogo2: class extends self.ISpriteInstance {},
	BotaoVoltar: class extends self.ISpriteInstance {},
	BotaoConquistas2: class extends self.ISpriteInstance {},
	bege: class extends self.ISpriteInstance {},
	BotaoOrientacao: class extends self.ISpriteInstance {},
	TelaMenuOrientacao: class extends self.ISpriteInstance {},
	DMMonoAvisoOrientacao: class extends self.ISpriteFontInstance {},
	DMMonoAvisoOrientacao2: class extends self.ISpriteFontInstance {},
	BotaoNegarOrientacao: class extends self.ISpriteInstance {},
	BotaoAceitarOrientacao: class extends self.ISpriteInstance {},
	DMMonoAjuda: class extends self.ISpriteFontInstance {},
	FundoBranco: class extends self.ISpriteInstance {},
	PontilhadoOrientacao: class extends self.ISpriteInstance {},
	TelaAjuda2: class extends self.ISpriteInstance {},
	TelaAjuda3: class extends self.ISpriteInstance {},
	TelaAjuda4: class extends self.ISpriteInstance {},
	TelaAjuda5: class extends self.ISpriteInstance {},
	TelaAjuda6: class extends self.ISpriteInstance {},
	TelaAjuda7: class extends self.ISpriteInstance {},
	TelaAjuda8: class extends self.ISpriteInstance {},
	Estrela: class extends self.ISpriteInstance {},
	HandTouch: class extends self.ISpriteInstance {},
	TrilhaLinha: class extends self.ISpriteInstance {},
	LimiteBombinha: class extends self.ISpriteInstance {},
	TelaMenuStartPortrait: class extends self.ISpriteInstance {},
	DMMonoAvisoStart: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	Pedra12: class extends self.ISpriteInstance {},
	Orbital: class extends self.ISpriteInstance {},
	PedraFake: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	PedraInterrogação: class extends self.ISpriteInstance {},
	PedraFake2: class extends self.ISpriteInstance {},
	Sequenciapedras: class extends self.ISpriteInstance {},
	EstrelaDestaque: class extends self.ISpriteInstance {},
	Pedras: class extends self.ISpriteInstance {},
	PedraPequena: class extends self.ISpriteInstance {},
	PedraMedia: class extends self.ISpriteInstance {},
	PedraGrande: class extends self.ISpriteInstance {},
	Botoes: class extends self.ISpriteInstance {},
	PedrasDois: class extends self.ISpriteInstance {},
	Hominhos: class extends self.ISpriteInstance {},
	Conquistas: class extends self.ISpriteInstance {},
	MenuConquistaEspecifico: class extends self.ISpriteInstance {},
	MenuConquistasGeral: class extends self.ISpriteInstance {},
	MenuVideo: class extends self.ISpriteInstance {}
}