const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Timeline,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.WeLoPlay_WSDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.WeLoPlay_WSDK.Acts.LoadingFinished,
		C3.Plugins.WeLoPlay_WSDK.Acts.HideLoader,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.IsPreview,
		C3.JavaScriptInEvents.GameEvents_Event4_Act1,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.PlatformInfo.Exps.CanvasCssWidth,
		C3.Plugins.PlatformInfo.Exps.CanvasCssHeight,
		C3.Plugins.PlatformInfo.Exps.DevicePixelRatio,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.System.Exps.imagememoryusage,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.UnloadObjectTextures,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsLeftRightKeyDown,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.WeLoPlay_WSDK.Cnds.RewardedAdEarned,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.WeLoPlay_WSDK.Acts.ShowInterstitialAd,
		C3.JavaScriptInEvents.Eaad_Event19_Act3,
		C3.JavaScriptInEvents.Eaad_Event20_Act3,
		C3.Plugins.WeLoPlay_WSDK.Acts.ShowRewardedAd,
		C3.JavaScriptInEvents.Eaad_Event25_Act3,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Eaad_Event26_Act4,
		C3.JavaScriptInEvents.Eaad_Event27_Act2,
		C3.JavaScriptInEvents.Eaad_Event29_Act1,
		C3.Plugins.WeLoPlay_WSDK.Acts.GameplayStart,
		C3.Plugins.WeLoPlay_WSDK.Acts.GameplayEnd,
		C3.Plugins.WeLoPlay_WSDK.Cnds.RewardedAdStarted,
		C3.Plugins.WeLoPlay_WSDK.Cnds.RewardedAdFinished,
		C3.Plugins.WeLoPlay_WSDK.Cnds.InterstitialAdStarted,
		C3.Plugins.WeLoPlay_WSDK.Cnds.InterstitialAdFinished,
		C3.Plugins.WeLoPlay_WSDK.Cnds.MuteAudioEvent,
		C3.Plugins.WeLoPlay_WSDK.Cnds.UnmuteAudioEvent
	];
};
self.C3_JsPropNameTable = [
	{id: 0},
	{category: 0},
	{enabled: 0},
	{Tween: 0},
	{buttonS1: 0},
	{buttonToolNp: 0},
	{uiStageProgressBackLine: 0},
	{uiStageProgressBackS: 0},
	{uiStageProgressIconS: 0},
	{maxW: 0},
	{progressBar: 0},
	{progressBarBack: 0},
	{buttonIcon: 0},
	{fakeLipsIcon: 0},
	{itemButtonS: 0},
	{itemsBorderButtonS: 0},
	{itemIconS: 0},
	{drawItemIconS: 0},
	{Sine: 0},
	{nextButton: 0},
	{active: 0},
	{nextButton2: 0},
	{nextButton3: 0},
	{preStepPickUIBackS: 0},
	{mainTiledBg: 0},
	{name: 0},
	{Rotate: 0},
	{indicator: 0},
	{use: 0},
	{pimple: 0},
	{stageScreenBgTb: 0},
	{preStepPickProgress: 0},
	{stageScreenButtonS: 0},
	{stageIconEffectS: 0},
	{stickerButtonS: 0},
	{itemsPanelAnchorTb: 0},
	{settingsBgS: 0},
	{soundIcon: 0},
	{stageScreenIconS: 0},
	{take_photo: 0},
	{tutorialHandS: 0},
	{textureIconBackS: 0},
	{actualItem: 0},
	{newId: 0},
	{baseScaleX: 0},
	{baseScaleY: 0},
	{index: 0},
	{clothes: 0},
	{loadingIcon: 0},
	{adIconS: 0},
	{stickerButtonAnchorTb: 0},
	{buttonSettingsClose: 0},
	{eyes: 0},
	{backButton: 0},
	{baseW: 0},
	{baseH: 0},
	{bodyAnchor: 0},
	{newBodyS: 0},
	{newClothesS: 0},
	{eyesParts: 0},
	{defaultClothes: 0},
	{camera_shoot: 0},
	{Confetti: 0},
	{Particles2: 0},
	{stickerPlaceParticle: 0},
	{backlip: 0},
	{creamBottle: 0},
	{lipstickBackS: 0},
	{toolS: 0},
	{toolDrawColliderS: 0},
	{toolDrawColliderS2: 0},
	{cream: 0},
	{dotCream: 0},
	{scar: 0},
	{teethBad: 0},
	{pencilS: 0},
	{pimpleCollider: 0},
	{lastPointer: 0},
	{lastPointer2: 0},
	{lastPointer3: 0},
	{lastPointer4: 0},
	{gradientDrawingCanvas: 0},
	{lipsBgCanvas: 0},
	{lipsGlitterCanvas: 0},
	{lipsOutlineCanvas: 0},
	{lipsOverlayCanvas: 0},
	{lipsRemoveOverlayCanvas: 0},
	{lipsBG: 0},
	{lipsOverlayS: 0},
	{load: 0},
	{lipsTextureS: 0},
	{lipsGlitterS: 0},
	{baseSize: 0},
	{canPlace: 0},
	{sticker: 0},
	{mouthS: 0},
	{lipsOverlayToRemove: 0},
	{lipsMaskS: 0},
	{lipsOutlineS: 0},
	{speed: 0},
	{angleOffset: 0},
	{angleOffsetTarget: 0},
	{baseAngle: 0},
	{lipsPart: 0},
	{paintPart: 0},
	{lipsPartsAnchor: 0},
	{WriteTimelinePlaceHolder: 0},
	{drawColliderS: 0},
	{lipsAreaHitMarkerS: 0},
	{isHitMarker: 0},
	{priority: 0},
	{lipsAreaMarkerS: 0},
	{lipsOverlayFinishTb: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Touch: 0},
	{Keyboard: 0},
	{TimelineController: 0},
	{Browser: 0},
	{bgLast: 0},
	{gradienDecor: 0},
	{TWEENER: 0},
	{Mouse: 0},
	{WSDK: 0},
	{PlatformInfo: 0},
	{debug1: 0},
	{debug2: 0},
	{lineFeelAnchor: 0},
	{hand: 0},
	{handBack: 0},
	{menuBg: 0},
	{menuButtonsAnchor: 0},
	{settingsBg: 0},
	{Audio: 0},
	{uiBg: 0},
	{stickerControls: 0},
	{Sprite3: 0},
	{currentClothes: 0},
	{emptyIcon: 0},
	{"9patch": 0},
	{Text: 0},
	{winButtonsAnchor: 0},
	{stickerFaceCollisionS: 0},
	{bgCanvas: 0},
	{bgTileTb: 0},
	{bgIconS: 0},
	{buttonBgCanvas: 0},
	{photoFrameS: 0},
	{photoFrameCanvas: 0},
	{photoFrameCanvas2: 0},
	{gameLogoS: 0},
	{Text2: 0},
	{Sprite4: 0},
	{bgGradientS: 0},
	{BUTTON_NP: 0},
	{BUTTON_S: 0},
	{CLOTHES_S: 0},
	{TEXT_T: 0},
	{IS_PREVIEW: 0},
	{didSetIsPreview: 0},
	{didGameStart: 0},
	{DidTapToStartGameplay: 0},
	{x: 0},
	{y: 0},
	{url: 0},
	{resize: 0},
	{w: 0},
	{h: 0},
	{IsInGameplay: 0},
	{tag: 0},
	{waitForTouch: 0},
	{size: 0},
	{canToggle: 0}
];

self.InstanceType = {
	buttonS1: class extends self.ISpriteInstance {},
	buttonToolNp: class extends self.I9PatchInstance {},
	uiStageProgressBackLine: class extends self.ITiledBackgroundInstance {},
	uiStageProgressBackS: class extends self.ISpriteInstance {},
	uiStageProgressIconS: class extends self.ISpriteInstance {},
	progressBar: class extends self.I9PatchInstance {},
	progressBarBack: class extends self.I9PatchInstance {},
	buttonIcon: class extends self.ISpriteInstance {},
	fakeLipsIcon: class extends self.ISpriteInstance {},
	itemButtonS: class extends self.ISpriteInstance {},
	itemsBorderButtonS: class extends self.ISpriteInstance {},
	itemIconS: class extends self.ISpriteInstance {},
	drawItemIconS: class extends self.ISpriteInstance {},
	nextButton: class extends self.ISpriteInstance {},
	nextButton2: class extends self.ISpriteInstance {},
	nextButton3: class extends self.ISpriteInstance {},
	preStepPickUIBackS: class extends self.ISpriteInstance {},
	mainTiledBg: class extends self.ITiledBackgroundInstance {},
	indicator: class extends self.ISpriteInstance {},
	pimple: class extends self.ISpriteInstance {},
	stageScreenBgTb: class extends self.ITiledBackgroundInstance {},
	preStepPickProgress: class extends self.I9PatchInstance {},
	stageScreenButtonS: class extends self.ISpriteInstance {},
	stageIconEffectS: class extends self.ISpriteInstance {},
	stickerButtonS: class extends self.ISpriteInstance {},
	itemsPanelAnchorTb: class extends self.ITiledBackgroundInstance {},
	settingsBgS: class extends self.ISpriteInstance {},
	soundIcon: class extends self.ISpriteInstance {},
	stageScreenIconS: class extends self.ISpriteInstance {},
	take_photo: class extends self.ISpriteInstance {},
	tutorialHandS: class extends self.ISpriteInstance {},
	textureIconBackS: class extends self.ISpriteInstance {},
	clothes: class extends self.ISpriteInstance {},
	loadingIcon: class extends self.ISpriteInstance {},
	adIconS: class extends self.ISpriteInstance {},
	stickerButtonAnchorTb: class extends self.ITiledBackgroundInstance {},
	buttonSettingsClose: class extends self.ISpriteInstance {},
	eyes: class extends self.ISpriteInstance {},
	backButton: class extends self.ISpriteInstance {},
	bodyAnchor: class extends self.ISpriteInstance {},
	newBodyS: class extends self.ISpriteInstance {},
	newClothesS: class extends self.ISpriteInstance {},
	eyesParts: class extends self.ISpriteInstance {},
	defaultClothes: class extends self.ISpriteInstance {},
	camera_shoot: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	stickerPlaceParticle: class extends self.IParticlesInstance {},
	backlip: class extends self.ISpriteInstance {},
	creamBottle: class extends self.ISpriteInstance {},
	lipstickBackS: class extends self.ISpriteInstance {},
	toolS: class extends self.ISpriteInstance {},
	toolDrawColliderS: class extends self.ISpriteInstance {},
	toolDrawColliderS2: class extends self.ISpriteInstance {},
	cream: class extends self.I9PatchInstance {},
	dotCream: class extends self.ISpriteInstance {},
	scar: class extends self.I9PatchInstance {},
	teethBad: class extends self.ISpriteInstance {},
	pencilS: class extends self.ISpriteInstance {},
	pimpleCollider: class extends self.ISpriteInstance {},
	lastPointer: class extends self.ISpriteInstance {},
	lastPointer2: class extends self.ISpriteInstance {},
	lastPointer3: class extends self.ISpriteInstance {},
	lastPointer4: class extends self.ISpriteInstance {},
	gradientDrawingCanvas: class extends self.IDrawingCanvasInstance {},
	lipsBgCanvas: class extends self.IDrawingCanvasInstance {},
	lipsGlitterCanvas: class extends self.IDrawingCanvasInstance {},
	lipsOutlineCanvas: class extends self.IDrawingCanvasInstance {},
	lipsOverlayCanvas: class extends self.IDrawingCanvasInstance {},
	lipsRemoveOverlayCanvas: class extends self.IDrawingCanvasInstance {},
	lipsBG: class extends self.ISpriteInstance {},
	lipsOverlayS: class extends self.ISpriteInstance {},
	lipsTextureS: class extends self.ISpriteInstance {},
	lipsGlitterS: class extends self.ISpriteInstance {},
	sticker: class extends self.ISpriteInstance {},
	mouthS: class extends self.ISpriteInstance {},
	lipsOverlayToRemove: class extends self.ISpriteInstance {},
	lipsMaskS: class extends self.ISpriteInstance {},
	lipsOutlineS: class extends self.ISpriteInstance {},
	lipsPart: class extends self.ISpriteInstance {},
	paintPart: class extends self.ISpriteInstance {},
	lipsPartsAnchor: class extends self.ISpriteInstance {},
	WriteTimelinePlaceHolder: class extends self.ISpriteInstance {},
	drawColliderS: class extends self.ISpriteInstance {},
	lipsAreaHitMarkerS: class extends self.ISpriteInstance {},
	lipsAreaMarkerS: class extends self.ISpriteInstance {},
	lipsOverlayFinishTb: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	bgLast: class extends self.ISpriteInstance {},
	gradienDecor: class extends self.ISpriteInstance {},
	TWEENER: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	WSDK: class extends C3.Plugins.WeLoPlay_WSDK.Instance {},
	PlatformInfo: class extends self.IInstance {},
	debug1: class extends self.ISpriteInstance {},
	debug2: class extends self.ISpriteInstance {},
	lineFeelAnchor: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	handBack: class extends self.ITiledBackgroundInstance {},
	menuBg: class extends self.ISpriteInstance {},
	menuButtonsAnchor: class extends self.ISpriteInstance {},
	settingsBg: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	uiBg: class extends self.I9PatchInstance {},
	stickerControls: class extends self.I9PatchInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	currentClothes: class extends self.ISpriteInstance {},
	emptyIcon: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	Text: class extends self.ITextInstance {},
	winButtonsAnchor: class extends self.ISpriteInstance {},
	stickerFaceCollisionS: class extends self.ISpriteInstance {},
	bgCanvas: class extends self.IDrawingCanvasInstance {},
	bgTileTb: class extends self.ITiledBackgroundInstance {},
	bgIconS: class extends self.ISpriteInstance {},
	buttonBgCanvas: class extends self.IDrawingCanvasInstance {},
	photoFrameS: class extends self.ISpriteInstance {},
	photoFrameCanvas: class extends self.IDrawingCanvasInstance {},
	photoFrameCanvas2: class extends self.IDrawingCanvasInstance {},
	gameLogoS: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bgGradientS: class extends self.ISpriteInstance {},
	BUTTON_NP: class extends self.I9PatchInstance {},
	BUTTON_S: class extends self.ISpriteInstance {},
	CLOTHES_S: class extends self.ISpriteInstance {},
	TEXT_T: class extends self.ITextInstance {}
}