const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.skymen_pokiSDK,
		C3.Plugins.Date,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.System.Cnds.PickNth,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.windowheight,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.DrawingCanvas.Acts.Line,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.skymen_pokiSDK.Acts.Rewarded,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.skymen_pokiSDK.Cnds.LastRewardedSuccess,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.LocalStorage.Cnds.OnCleared,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStop,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStart,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.skymen_pokiSDK.Acts.Interstitial,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.JavaScriptInEvents.Loadingevt_Event2_Act1,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.ObjectTypeName,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{DrawingCanvas: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{AJAX: 0},
	{PokiSDK2: 0},
	{Date2: 0},
	{indNapretkaPodloga: 0},
	{indNapretkaTrofej: 0},
	{indNapretkaCrta: 0},
	{DragDrop: 0},
	{indNapretkaPoint: 0},
	{slider_ID: 0},
	{val: 0},
	{min: 0},
	{max: 0},
	{step: 0},
	{slider: 0},
	{slider_bar: 0},
	{value_display: 0},
	{type: 0},
	{Sine: 0},
	{Sine2: 0},
	{Button: 0},
	{id: 0},
	{itemStyle: 0},
	{origWidth: 0},
	{origHeight: 0},
	{cena: 0},
	{Pin: 0},
	{Flash: 0},
	{Timer: 0},
	{uniButton: 0},
	{panelBckg: 0},
	{Fade: 0},
	{pageIndicator: 0},
	{stripeWinOrLose: 0},
	{Posveta_ispod_snimka: 0},
	{HintsTxt: 0},
	{Text: 0},
	{svrha: 0},
	{purpose: 0},
	{SpriteFontMy: 0},
	{spriteFontBig: 0},
	{indNapretkaTekst: 0},
	{Neprijatelj: 0},
	{unistavajRedom: 0},
	{mojaBaza: 0},
	{Touched: 0},
	{DrawPoint: 0},
	{Unlocked: 0},
	{Double: 0},
	{Reversed: 0},
	{Gal: 0},
	{Scale: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Confetti: 0},
	{Small: 0},
	{NoDestroy: 0},
	{Slika: 0},
	{Pointer: 0},
	{pocX: 0},
	{pocY: 0},
	{ciljX: 0},
	{ciljY: 0},
	{aktivan: 0},
	{MoveTo: 0},
	{tutorijalHand: 0},
	{TiledBackground: 0},
	{TiledSplash: 0},
	{miniHand: 0},
	{pokretniSprajt: 0},
	{gameLogo: 0},
	{arrNivoi: 0},
	{arrTekstUIgri: 0},
	{Family1: 0},
	{Tween: 0},
	{Tekstovi: 0},
	{Sound: 0},
	{Date: 0},
	{FirstStart: 0},
	{Level: 0},
	{PhotoMode: 0},
	{BrojPivotTacaka: 0},
	{TrenutnoCrtam: 0},
	{PreostaloMastila: 0},
	{UtrosenoMastila: 0},
	{LastY: 0},
	{LastX: 0},
	{PrviX: 0},
	{PrviY: 0},
	{InterstitialAdID: 0},
	{hintCount: 0},
	{rewardAdDajeHintova: 0},
	{lastLevel: 0},
	{nivoZavrsen: 0},
	{deltaX: 0},
	{deltaY: 0},
	{duzinaLinije: 0},
	{tgA: 0},
	{nacrtanaLinija: 0},
	{tipNacrtaneLinije: 0},
	{kolikoJosImaNeprijatelja: 0},
	{dist: 0},
	{newSoundStatus: 0},
	{AllUnlocked: 0},
	{dragging: 0},
	{thumbSirina: 0},
	{idSlikeZaSnimanje: 0},
	{thumbVisina: 0},
	{donjaGranicaY: 0},
	{gornjaGranicaY: 0},
	{otkljucaniNivo: 0},
	{frejmDuplogObjekta: 0},
	{d: 0},
	{POKI_GAMEPLAY_STOPPED: 0},
	{loadingComplete: 0},
	{layersToShow: 0},
	{panelTopText: 0},
	{panelBackgroundFrame: 0},
	{spriteFontSize: 0},
	{daLiDaPauziram: 0},
	{fieldPurpose: 0},
	{valueToWrite: 0},
	{formattedNumber: 0},
	{tempNum: 0},
	{decimale: 0},
	{number: 0},
	{efekatKlika: 0},
	{tempWidth: 0},
	{tempHeight: 0},
	{startTime: 0},
	{buttonUID: 0},
	{locStorageNameBase: 0},
	{LANGUAGE_ID: 0},
	{SOUND_STATUS: 0},
	{MUSIC_STATUS: 0},
	{initCounter: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	PokiSDK2: class extends C3.Plugins.skymen_pokiSDK.Instance {},
	Date2: class extends self.IInstance {},
	indNapretkaPodloga: class extends self.ISpriteInstance {},
	indNapretkaTrofej: class extends self.ISpriteInstance {},
	indNapretkaCrta: class extends self.ISpriteInstance {},
	indNapretkaPoint: class extends self.ISpriteInstance {},
	slider: class extends self.ISpriteInstance {},
	slider_bar: class extends self.ISpriteInstance {},
	value_display: class extends self.ITextInstance {},
	Button: class extends self.ISpriteInstance {},
	uniButton: class extends self.ISpriteInstance {},
	panelBckg: class extends self.ISpriteInstance {},
	pageIndicator: class extends self.ISpriteInstance {},
	stripeWinOrLose: class extends self.ISpriteInstance {},
	Posveta_ispod_snimka: class extends self.ISpriteInstance {},
	HintsTxt: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	SpriteFontMy: class extends self.ISpriteFontInstance {},
	spriteFontBig: class extends self.ISpriteFontInstance {},
	indNapretkaTekst: class extends self.ITextInstance {},
	Neprijatelj: class extends self.ISpriteInstance {},
	mojaBaza: class extends self.ISpriteInstance {},
	DrawPoint: class extends self.ISpriteInstance {},
	Gal: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Slika: class extends self.ISpriteInstance {},
	Pointer: class extends self.ISpriteInstance {},
	tutorijalHand: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledSplash: class extends self.ITiledBackgroundInstance {},
	miniHand: class extends self.ISpriteInstance {},
	pokretniSprajt: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	arrNivoi: class extends self.IArrayInstance {},
	arrTekstUIgri: class extends self.IArrayInstance {},
	Family1: class extends self.ISpriteInstance {},
	Tekstovi: class extends self.ISpriteFontInstance {}
}